apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: api_monitoring
    user: api_monitor
    secureJsonData:
      password: 'monitor123'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
    editable: true

